name: E2E CI

on:
  push:
    branches:
    - github-actions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up testdb -d
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install Packages
        working-directory: ./app
        run: npm ci
      - name: Build app
        working-directory: ./app
        run: npm run build --if-present
      - name: Run E2E test
        working-directory: ./app
        run: npm run test:e2e --ci --reporters=default --reporters=jest-junit
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests Report
          path: app/reports/*.xml
          reporter: jest-junit
